const readonlyGlobals = Object.fromEntries(
  [
    "AbortController",
    "AbortSignal",
    "Blob",
    "BroadcastChannel",
    "Buffer",
    "CompressionStream",
    "CustomEvent",
    "DOMException",
    "DecompressionStream",
    "Event",
    "EventTarget",
    "File",
    "FormData",
    "Headers",
    "MessageChannel",
    "MessageEvent",
    "MessagePort",
    "Performance",
    "PerformanceEntry",
    "PerformanceMark",
    "PerformanceMeasure",
    "PerformanceObserver",
    "PerformanceObserverEntryList",
    "PerformanceResourceTiming",
    "ReadableStream",
    "Request",
    "Response",
    "TextDecoder",
    "TextEncoder",
    "TransformStream",
    "URL",
    "URLSearchParams",
    "WebAssembly",
    "WritableStream",
    "atob",
    "btoa",
    "clearImmediate",
    "clearInterval",
    "clearTimeout",
    "console",
    "crypto",
    "fetch",
    "global",
    "globalThis",
    "navigator",
    "performance",
    "process",
    "queueMicrotask",
    "setImmediate",
    "setInterval",
    "setTimeout",
    "structuredClone",
  ].map((name) => [name, "readonly"]),
);

export default [
  {
    files: ["src/**/*.mjs", "test/**/*.mjs"],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "module",
      globals: readonlyGlobals,
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-var": "error",
      "prefer-const": "warn",
    },
  },
];
